import { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('en');
  const toggleLang = () => setLang(l => l === 'en' ? 'hi' : 'en');
  return (
    <LanguageContext.Provider value={{ lang, toggleLang }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLang() {
  return useContext(LanguageContext);
}

// ─── Master Translation Dictionary ────────────────────────────────────────────
export const t = {

  // ── Common / Shared ──────────────────────────────────────────────────────
  'PS-CRM Gov Portal':              { hi: 'पीएस-सीआरएम सरकारी पोर्टल' },
  'Smart Public Service CRM':       { hi: 'स्मार्ट सार्वजनिक सेवा सीआरएम' },
  'PS-CRM':                         { hi: 'पीएस-सीआरएम' },
  'Public Service CRM':             { hi: 'सार्वजनिक सेवा सीआरएम' },
  'Centralized Grievance Management': { hi: 'केंद्रीकृत शिकायत प्रबंधन' },
  'Government of Delhi':            { hi: 'दिल्ली सरकार' },
  'Ministry of Personnel, Public Grievances & Pensions': { hi: 'कार्मिक, लोक शिकायत और पेंशन मंत्रालय' },
  'Government of Delhi · Ministry of Personnel, Public Grievances & Pensions': { hi: 'दिल्ली सरकार · कार्मिक, लोक शिकायत और पेंशन मंत्रालय' },
  'Login': { hi: 'लॉगिन' },
  'Logout': { hi: 'लॉगआउट' },
  'Register': { hi: 'पंजीकरण' },
  'Submit': { hi: 'जमा करें' },
  'Track': { hi: 'ट्रैक करें' },
  'Dashboard': { hi: 'डैशबोर्ड' },
  'Home': { hi: 'होम' },
  'Features': { hi: 'विशेषताएं' },
  'Notifications': { hi: 'सूचनाएं' },
  'Loading...': { hi: 'लोड हो रहा है...' },
  'Pending': { hi: 'लंबित' },
  'In Progress': { hi: 'प्रगति में' },
  'Resolved': { hi: 'हल किया गया' },
  'Escalated': { hi: 'एस्केलेट किया गया' },
  'High': { hi: 'उच्च' },
  'Medium': { hi: 'मध्यम' },
  'Low': { hi: 'निम्न' },
  'Roads': { hi: 'सड़कें' },
  'Water': { hi: 'जल' },
  'Electricity': { hi: 'बिजली' },
  'Sanitation': { hi: 'स्वच्छता' },
  'Other': { hi: 'अन्य' },
  'All': { hi: 'सभी' },
  'Cancel': { hi: 'रद्द करें' },
  'Search': { hi: 'खोजें' },
  'Refresh': { hi: 'रिफ्रेश' },
  'Export': { hi: 'निर्यात' },
  'Print': { hi: 'प्रिंट' },
  'NAVIGATION': { hi: 'नेविगेशन' },
  'MY ACCOUNT': { hi: 'मेरा खाता' },
  'MY WORK': { hi: 'मेरा काम' },
  'MAIN MENU': { hi: 'मुख्य मेनू' },
  'Administrator': { hi: 'प्रशासक' },
  'Admin Portal': { hi: 'एडमिन पोर्टल' },
  'Citizen Portal': { hi: 'नागरिक पोर्टल' },
  'Officer Portal': { hi: 'अधिकारी पोर्टल' },
  'Submit Complaint': { hi: 'शिकायत दर्ज करें' },
  'Track Complaint': { hi: 'शिकायत ट्रैक करें' },
  'Public Dashboard': { hi: 'सार्वजनिक डैशबोर्ड' },
  'My Dashboard': { hi: 'मेरा डैशबोर्ड' },
  'All Complaints': { hi: 'सभी शिकायतें' },
  'My Complaints': { hi: 'मेरी शिकायतें' },
  'File Complaint': { hi: 'शिकायत दर्ज करें' },
  'View Cases': { hi: 'मामले देखें' },
  'Officers': { hi: 'अधिकारी' },
  'Analytics': { hi: 'विश्लेषण' },

  // ── Home Page ────────────────────────────────────────────────────────────
  'Your Complaints, Resolved Transparently with AI Intelligence': { hi: 'आपकी शिकायतें, AI बुद्धिमत्ता से पारदर्शी रूप से हल की गईं' },
  'Resolved Transparently': { hi: 'पारदर्शी रूप से हल किया गया' },
  'PS-CRM is a centralized AI command center for citizen grievance management — NLP auto-classifies complaints, routes them to the right officer instantly, and ensures transparent end-to-end resolution.': { hi: 'पीएस-सीआरएम नागरिक शिकायत प्रबंधन के लिए एक केंद्रीकृत AI कमांड सेंटर है — NLP स्वचालित रूप से शिकायतों को वर्गीकृत करता है, उन्हें तुरंत सही अधिकारी के पास भेजता है और पारदर्शी समाधान सुनिश्चित करता है।' },
  '📝 File a Complaint →': { hi: '📝 शिकायत दर्ज करें →' },
  '🔍 Track Your Complaint': { hi: '🔍 अपनी शिकायत ट्रैक करें' },
  'PLATFORM STATISTICS · LIVE': { hi: 'प्लेटफ़ॉर्म सांख्यिकी · लाइव' },
  'Complaints Tracked': { hi: 'शिकायतें ट्रैक की गईं' },
  'Resolution Rate': { hi: 'समाधान दर' },
  'How It Works': { hi: 'यह कैसे काम करता है' },
  'Simple 4-step process to resolve your grievance': { hi: 'आपकी शिकायत हल करने की सरल 4-चरण प्रक्रिया' },
  'Frequently Asked Questions': { hi: 'अक्सर पूछे जाने वाले प्रश्न' },
  'Everything you need to know about PS-CRM': { hi: 'PS-CRM के बारे में आपको जो कुछ जानना चाहिए' },
  'Register / Login →': { hi: 'पंजीकरण / लॉगिन →' },
  'Quick Links': { hi: 'त्वरित लिंक' },
  'Contact': { hi: 'संपर्क' },
  'Raise Complaint': { hi: 'शिकायत दर्ज करें' },
  'Track Status': { hi: 'स्थिति ट्रैक करें' },
  'File a Complaint': { hi: 'शिकायत दर्ज करें' },
  'How do I track my complaint?': { hi: 'मैं अपनी शिकायत कैसे ट्रैक करूं?' },
  'Can I re-raise a complaint?': { hi: 'क्या मैं शिकायत फिर से दर्ज कर सकता हूं?' },
  'What departments are covered?': { hi: 'कौन से विभाग शामिल हैं?' },
  'Is my personal information safe?': { hi: 'क्या मेरी व्यक्तिगत जानकारी सुरक्षित है?' },
  'How do I provide feedback after resolution?': { hi: 'समाधान के बाद मैं फ़ीडबैक कैसे दूं?' },
  '🇮🇳 Digital India · AI-Powered Governance · 2025': { hi: '🇮🇳 डिजिटल इंडिया · AI-संचालित शासन · 2025' },
  'Building trust between citizens and': { hi: 'नागरिकों और' },
  'Government of Delhi through technology.': { hi: 'दिल्ली सरकार के बीच प्रौद्योगिकी से विश्वास बनाना।' },
  '© 2026 Government of Delhi – Smart Public Service CRM. All rights reserved.': { hi: '© 2026 दिल्ली सरकार – स्मार्ट सार्वजनिक सेवा सीआरएम। सर्वाधिकार सुरक्षित।' },

  // ── Feature Cards ────────────────────────────────────────────────────────
  'Submit Now →': { hi: 'अभी जमा करें →' },
  'Track Status →': { hi: 'स्थिति ट्रैक करें →' },
  'Open Dashboard →': { hi: 'डैशबोर्ड खोलें →' },
  'Learn More →': { hi: 'और जानें →' },
  '🔐 Login Required': { hi: '🔐 लॉगिन आवश्यक' },
  'Submit via web, app, WhatsApp or SMS in any language. AI handles classification.': { hi: 'वेब, ऐप, व्हाट्सएप या SMS से किसी भी भाषा में जमा करें। AI वर्गीकरण करता है।' },
  "Enter your PSCRM-ID to see real-time progress, SLA countdown and proof.": { hi: 'रियल-टाइम प्रगति, SLA काउंटडाउन और प्रमाण देखने के लिए अपना PSCRM-ID दर्ज करें।' },
  'Live ward rankings, complaint heatmaps and resolution analytics — no login needed.': { hi: 'लाइव वार्ड रैंकिंग, शिकायत हीटमैप और समाधान विश्लेषण — लॉगिन की आवश्यकता नहीं।' },
  'Understand the 6-step automated grievance lifecycle from submission to resolution.': { hi: 'जमा करने से समाधान तक 6-चरण स्वचालित शिकायत जीवनचक्र समझें।' },

  // ── How It Works Steps ───────────────────────────────────────────────────
  'AI Processing': { hi: 'AI प्रसंस्करण' },
  'Resolution': { hi: 'समाधान' },
  'Feedback': { hi: 'प्रतिक्रिया' },
  'File your complaint online with details and photos': { hi: 'विवरण और फ़ोटो के साथ ऑनलाइन शिकायत दर्ज करें' },
  'Auto-categorized and routed to the right department': { hi: 'स्वतः वर्गीकृत और सही विभाग को भेजा गया' },
  'Officer works on it with live SLA tracking': { hi: 'अधिकारी लाइव SLA ट्रैकिंग के साथ काम करता है' },
  'Rate the resolution and provide your feedback': { hi: 'समाधान को रेट करें और अपना फ़ीडबैक दें' },

  // ── Citizen Dashboard ────────────────────────────────────────────────────
  'Total Filed': { hi: 'कुल दर्ज' },
  'New Complaint': { hi: 'नई शिकायत' },
  '➕ New Complaint': { hi: '➕ नई शिकायत' },
  'Report a new issue': { hi: 'नई समस्या रिपोर्ट करें' },
  'Check complaint status': { hi: 'शिकायत की स्थिति जांचें' },
  'Rate resolved complaints': { hi: 'हल की गई शिकायतों को रेट करें' },
  'View transparency data': { hi: 'पारदर्शिता डेटा देखें' },
  'Give Feedback': { hi: 'फ़ीडबैक दें' },
  'Public Report': { hi: 'सार्वजनिक रिपोर्ट' },
  '📋 My Complaints': { hi: '📋 मेरी शिकायतें' },
  'No complaints yet': { hi: 'अभी कोई शिकायत नहीं' },
  'File your first complaint to get started': { hi: 'शुरू करने के लिए अपनी पहली शिकायत दर्ज करें' },
  '📝 File First Complaint': { hi: '📝 पहली शिकायत दर्ज करें' },
  '🔍 Track': { hi: '🔍 ट्रैक करें' },
  '⭐ Feedback': { hi: '⭐ फ़ीडबैक' },
  '👤 Citizen': { hi: '👤 नागरिक' },
  'SLA:': { hi: 'एसएलए:' },

  // ── Submit Complaint ─────────────────────────────────────────────────────
  '📝 File a Complaint': { hi: '📝 शिकायत दर्ज करें' },
  'Describe your issue — AI will automatically detect the category and urgency': { hi: 'अपनी समस्या बताएं — AI स्वतः श्रेणी और जरूरी प्रकृति का पता लगाएगा' },
  '📋 Complaint Details': { hi: '📋 शिकायत विवरण' },
  'Complaint Title *': { hi: 'शिकायत का शीर्षक *' },
  'Brief title of your complaint': { hi: 'अपनी शिकायत का संक्षिप्त शीर्षक' },
  'Complaint Description *': { hi: 'शिकायत का विवरण *' },
  'Describe your issue in detail — AI will auto-detect category and urgency...': { hi: 'अपनी समस्या विस्तार से बताएं — AI श्रेणी और जरूरी प्रकृति स्वतः पहचानेगा...' },
  '🧠 AI Analyzing...': { hi: '🧠 AI विश्लेषण कर रहा है...' },
  'Detecting category and urgency...': { hi: 'श्रेणी और जरूरी प्रकृति का पता लगाया जा रहा है...' },
  '🧠 AI Auto-Classification': { hi: '🧠 AI स्वतः वर्गीकरण' },
  'Category': { hi: 'श्रेणी' },
  'Department': { hi: 'विभाग' },
  'Urgency': { hi: 'जरूरी प्रकृति' },
  'Category (AI detected ✨)': { hi: 'श्रेणी (AI द्वारा पहचाना ✨)' },
  'Urgency (AI detected ✨)': { hi: 'जरूरी प्रकृति (AI द्वारा पहचाना ✨)' },
  '📸 Photo Evidence': { hi: '📸 फ़ोटो साक्ष्य' },
  '(Optional — max 3 images)': { hi: '(वैकल्पिक — अधिकतम 3 फ़ोटो)' },
  'Click or drag & drop images here': { hi: 'यहाँ क्लिक करें या फ़ोटो खींचकर छोड़ें' },
  'Drop images here!': { hi: 'फ़ोटो यहाँ छोड़ें!' },
  'JPG, PNG, WEBP · Max 3 images · 5MB each': { hi: 'JPG, PNG, WEBP · अधिकतम 3 फ़ोटो · 5MB प्रत्येक' },
  'Add more': { hi: 'और जोड़ें' },
  '📍 Location Details': { hi: '📍 स्थान विवरण' },
  'Address': { hi: 'पता' },
  'Street, area or landmark': { hi: 'सड़क, क्षेत्र या स्थल' },
  'Ward': { hi: 'वार्ड' },
  'Ward number or name': { hi: 'वार्ड नंबर या नाम' },
  '👤 Your Details': { hi: '👤 आपका विवरण' },
  'Full Name *': { hi: 'पूरा नाम *' },
  'Your full name': { hi: 'आपका पूरा नाम' },
  'Email *': { hi: 'ईमेल *' },
  'Your email': { hi: 'आपका ईमेल' },
  'Phone Number': { hi: 'फ़ोन नंबर' },
  '10-digit mobile number': { hi: '10 अंकों का मोबाइल नंबर' },
  '✅ Submit Complaint': { hi: '✅ शिकायत जमा करें' },
  '⏳ Submitting...': { hi: '⏳ जमा हो रहा है...' },
  '🤖 AI Auto-Classification': { hi: '🤖 AI स्वतः वर्गीकरण' },
  'Just describe your complaint — our AI automatically detects the category, department, and urgency level for you.': { hi: 'बस अपनी शिकायत बताएं — हमारा AI आपके लिए श्रेणी, विभाग और जरूरी स्तर स्वतः पहचानेगा।' },
  'ℹ️ How It Works': { hi: 'ℹ️ यह कैसे काम करता है' },
  'Describe Your Issue': { hi: 'अपनी समस्या बताएं' },
  'Type your complaint title and description': { hi: 'अपनी शिकायत का शीर्षक और विवरण लिखें' },
  'AI Auto-Classifies': { hi: 'AI स्वतः वर्गीकृत करता है' },
  'Category & urgency detected instantly': { hi: 'श्रेणी और जरूरी स्तर तुरंत पहचाना गया' },
  'Add Photo Evidence': { hi: 'फ़ोटो साक्ष्य जोड़ें' },
  'Attach photos for faster resolution': { hi: 'तेज़ समाधान के लिए फ़ोटो संलग्न करें' },
  'Track & Get Feedback': { hi: 'ट्रैक करें और फ़ीडबैक पाएं' },
  'Monitor status and rate the resolution': { hi: 'स्थिति देखें और समाधान को रेट करें' },
  'SLA Guidelines': { hi: 'SLA दिशानिर्देश' },
  'High Urgency': { hi: 'उच्च जरूरी' },
  'Medium Urgency': { hi: 'मध्यम जरूरी' },
  'Low Urgency': { hi: 'निम्न जरूरी' },
  'Complaint Submitted Successfully!': { hi: 'शिकायत सफलतापूर्वक जमा की गई!' },
  'Your complaint has been registered and assigned for review.': { hi: 'आपकी शिकायत पंजीकृत हो गई है और समीक्षा के लिए सौंपी गई है।' },
  'Complaint ID': { hi: 'शिकायत आईडी' },
  'Title': { hi: 'शीर्षक' },
  'Status': { hi: 'स्थिति' },
  'Pending Review': { hi: 'समीक्षा लंबित' },
  'Evidence Images': { hi: 'साक्ष्य फ़ोटो' },
  'SLA Deadline': { hi: 'SLA समय सीमा' },
  '🔍 Track Complaint': { hi: '🔍 शिकायत ट्रैक करें' },
  '➕ Submit Another': { hi: '➕ एक और जमा करें' },

  // ── Track Complaint ──────────────────────────────────────────────────────
  'Enter your complaint ID to see real-time status, photos, and progress report': { hi: 'रियल-टाइम स्थिति, फ़ोटो और प्रगति रिपोर्ट देखने के लिए शिकायत आईडी दर्ज करें' },

  'Enter your complaint ID (e.g. 69abc363f6b84bff71705289)': { hi: 'अपनी शिकायत आईडी दर्ज करें' },
  '⏳ Searching...': { hi: '⏳ खोज रहा है...' },
  '👤 Citizen Info': { hi: '👤 नागरिक जानकारी' },
  '⏱️ SLA Status': { hi: '⏱️ SLA स्थिति' },
  '📊 Quick Stats': { hi: '📊 त्वरित आँकड़े' },
  '🔔 Need Help?': { hi: '🔔 मदद चाहिए?' },
  '📅 Progress Timeline': { hi: '📅 प्रगति समयरेखा' },
  '📸 Evidence Photos': { hi: '📸 साक्ष्य फ़ोटो' },
  'Track Your Complaint': { hi: 'अपनी शिकायत ट्रैक करें' },
  'Enter the complaint ID you received after submission to see real-time status, photos, and full progress timeline': { hi: 'जमा करने के बाद मिली शिकायत आईडी दर्ज करें' },
  'Complaint Filed': { hi: 'शिकायत दर्ज की गई' },
  'Officer Assigned': { hi: 'अधिकारी नियुक्त किया गया' },
  'Work In Progress': { hi: 'काम जारी है' },
  'Complaint Resolved': { hi: 'शिकायत हल की गई' },
  'Awaiting Resolution': { hi: 'समाधान की प्रतीक्षा' },
  'remaining until deadline': { hi: 'समय सीमा तक बाकी' },
  'Complaint resolved successfully': { hi: 'शिकायत सफलतापूर्वक हल की गई' },
  'SLA deadline has passed': { hi: 'SLA समय सीमा बीत चुकी है' },
  '🎉 Closed on time': { hi: '🎉 समय पर बंद किया गया' },
  '🚨 Escalated to supervisor': { hi: '🚨 पर्यवेक्षक को एस्केलेट किया गया' },
  '✅ Within SLA timeline': { hi: '✅ SLA समयरेखा में' },
  'Days Open': { hi: 'खुले दिन' },
  'Photos Attached': { hi: 'फ़ोटो संलग्न' },
  'Priority': { hi: 'प्राथमिकता' },
  'Submitted On': { hi: 'जमा किया गया' },
  'Description': { hi: 'विवरण' },
  '✅ Resolution Note': { hi: '✅ समाधान नोट' },
  '🖨️ Print / Save Report': { hi: '🖨️ रिपोर्ट प्रिंट / सहेजें' },  '📧 Report Duplicate': { hi: '📧 डुप्लिकेट रिपोर्ट करें' },  '� Email Report': { hi: '📧 रिपोर्ट ईमेल करें' },
  '�🖨️ Download Report': { hi: '🖨️ रिपोर्ट डाउनलोड करें' },
  '📝 File New Complaint': { hi: '📝 नई शिकायत दर्ज करें' },
  'If your complaint is overdue or you need assistance:': { hi: 'यदि आपकी शिकायत समय से अधिक हो गई है या आपको सहायता की आवश्यकता है:' },
  '💡 Click any photo to view full size': { hi: '💡 पूर्ण आकार में देखने के लिए किसी भी फ़ोटो पर क्लिक करें' },

  // ── Feedback ─────────────────────────────────────────────────────────────
  '⭐ Rate Your Experience': { hi: '⭐ अपना अनुभव रेट करें' },
  'Help us improve by sharing your feedback': { hi: 'अपना फ़ीडबैक साझा करके हमें बेहतर बनाने में मदद करें' },
  '⭐ Overall Rating': { hi: '⭐ समग्र रेटिंग' },
  '👍 What went well? (Optional)': { hi: '👍 क्या अच्छा रहा? (वैकल्पिक)' },
  '💬 Additional Comments (Optional)': { hi: '💬 अतिरिक्त टिप्पणियां (वैकल्पिक)' },
  'Share your experience in detail...': { hi: 'अपना अनुभव विस्तार से साझा करें...' },
  '✅ Submit Feedback': { hi: '✅ फ़ीडबैक जमा करें' },
  'ℹ️ Why Your Feedback Matters': { hi: 'ℹ️ आपका फ़ीडबैक क्यों मायने रखता है' },
  'Improve Services': { hi: 'सेवाएं सुधारें' },
  'Officer Performance': { hi: 'अधिकारी प्रदर्शन' },
  'Policy Changes': { hi: 'नीति परिवर्तन' },
  'Reward Excellence': { hi: 'उत्कृष्टता पुरस्कृत करें' },
  'Platform Ratings': { hi: 'प्लेटफ़ॉर्म रेटिंग' },
  'Average Rating': { hi: 'औसत रेटिंग' },
  'Total Reviews': { hi: 'कुल समीक्षाएं' },
  'Satisfaction Rate': { hi: 'संतुष्टि दर' },
  '🔔 What Happens Next?': { hi: '🔔 आगे क्या होगा?' },
  'Thank You for Your Feedback!': { hi: 'आपके फ़ीडबैक के लिए धन्यवाद!' },
  'Your feedback helps us improve public services for everyone.': { hi: 'आपका फ़ीडबैक सभी के लिए सार्वजनिक सेवाएं बेहतर बनाने में मदद करता है।' },
  '📊 My Dashboard': { hi: '📊 मेरा डैशबोर्ड' },
  '📝 New Complaint': { hi: '📝 नई शिकायत' },
  'Very Poor': { hi: 'बहुत खराब' },
  'Poor': { hi: 'खराब' },
  'Average': { hi: 'औसत' },
  'Good': { hi: 'अच्छा' },
  'Excellent': { hi: 'उत्कृष्ट' },
  'Please select a rating': { hi: 'कृपया रेटिंग चुनें' },

  // ── Admin Dashboard ──────────────────────────────────────────────────────
  'Dashboard Overview': { hi: 'डैशबोर्ड अवलोकन' },
  'Total Complaints': { hi: 'कुल शिकायतें' },
  '🔄 Refresh': { hi: '🔄 रिफ्रेश' },
  '📊 Complaints by Category': { hi: '📊 श्रेणी के अनुसार शिकायतें' },
  '🎯 Complaints by Urgency': { hi: '🎯 जरूरी प्रकृति के अनुसार शिकायतें' },
  '📈 Daily Trend (Last 7 Days)': { hi: '📈 दैनिक प्रवृत्ति (पिछले 7 दिन)' },
  '📍 Complaints by Ward': { hi: '📍 वार्ड के अनुसार शिकायतें' },
  '🕐 Recent Complaints': { hi: '🕐 हाल की शिकायतें' },
  'View All →': { hi: 'सभी देखें →' },
  'Failed to load dashboard data. Make sure backend is running.': { hi: 'डैशबोर्ड डेटा लोड नहीं हो सका। बैकएंड चल रहा है सुनिश्चित करें।' },
  'Citizen': { hi: 'नागरिक' },
  'Date': { hi: 'दिनांक' },

  // ── Complaints List ──────────────────────────────────────────────────────
  '📋 All Complaints': { hi: '📋 सभी शिकायतें' },
  'Manage, assign and update all citizen complaints': { hi: 'सभी नागरिक शिकायतों को प्रबंधित, असाइन और अपडेट करें' },
  '🔍 Search by title or citizen name...': { hi: '🔍 शीर्षक या नागरिक नाम से खोजें...' },
  'Showing': { hi: 'दिखाया जा रहा है' },
  'of': { hi: 'में से' },
  'complaints': { hi: 'शिकायतें' },
  '✕ Clear': { hi: '✕ साफ़ करें' },
  'Assign Officer': { hi: 'अधिकारी असाइन करें' },
  '— Unassigned —': { hi: '— असाइन नहीं —' },
  'Change Status': { hi: 'स्थिति बदलें' },
  'No complaints found': { hi: 'कोई शिकायत नहीं मिली' },

  // ── Officer Management ───────────────────────────────────────────────────
  '🧑‍💼 Officer Management': { hi: '🧑‍💼 अधिकारी प्रबंधन' },
  'Manage field officers and their department assignments': { hi: 'फील्ड अधिकारियों और उनके विभाग असाइनमेंट का प्रबंधन करें' },
  '➕ Add New Officer': { hi: '➕ नया अधिकारी जोड़ें' },
  '🔑 Assign Role to Existing User': { hi: '🔑 मौजूदा उपयोगकर्ता को भूमिका असाइन करें' },
  'Promote any registered citizen to Officer or Admin. Only you can do this.': { hi: 'किसी भी पंजीकृत नागरिक को अधिकारी या एडमिन बनाएं। केवल आप यह कर सकते हैं।' },
  'Enter registered email address': { hi: 'पंजीकृत ईमेल पता दर्ज करें' },
  '✅ Assign Role': { hi: '✅ भूमिका असाइन करें' },
  '⏳ Assigning...': { hi: '⏳ असाइन हो रहा है...' },
  'Total Officers': { hi: 'कुल अधिकारी' },
  'Active': { hi: 'सक्रिय' },
  'Departments': { hi: 'विभाग' },
  'Avg Complaints': { hi: 'औसत शिकायतें' },
  'Assigned': { hi: 'असाइन किए गए' },
  'Register a field officer account': { hi: 'फील्ड अधिकारी खाता पंजीकृत करें' },
  '✅ Create Officer': { hi: '✅ अधिकारी बनाएं' },
  '⏳ Creating...': { hi: '⏳ बन रहा है...' },
  'Officer full name': { hi: 'अधिकारी का पूरा नाम' },
  'Officer email': { hi: 'अधिकारी का ईमेल' },
  'Set a password': { hi: 'पासवर्ड सेट करें' },
  '10-digit mobile': { hi: '10 अंकों का मोबाइल' },
  'Department *': { hi: 'विभाग *' },
  'Add New Officer': { hi: 'नया अधिकारी जोड़ें' },

  // ── Analytics ────────────────────────────────────────────────────────────
  '📈 Analytics Report': { hi: '📈 विश्लेषण रिपोर्ट' },
  'Comprehensive insights and performance metrics': { hi: 'व्यापक अंतर्दृष्टि और प्रदर्शन मेट्रिक्स' },
  '⬇️ Export Report': { hi: '⬇️ रिपोर्ट निर्यात करें' },
  '⏳ Exporting...': { hi: '⏳ निर्यात हो रहा है...' },
  'Avg Resolution': { hi: 'औसत समाधान' },
  'Average days': { hi: 'औसत दिन' },
  'All time': { hi: 'कुल समय' },
  'Awaiting action': { hi: 'कार्रवाई की प्रतीक्षा' },
  'Being resolved': { hi: 'हल किया जा रहा है' },
  'SLA breached': { hi: 'SLA उल्लंघन' },
  '📅 Complaint Volume Trend': { hi: '📅 शिकायत मात्रा प्रवृत्ति' },
  '🎯 Status Breakdown': { hi: '🎯 स्थिति विश्लेषण' },
  '⚡ Urgency Distribution': { hi: '⚡ जरूरी वितरण' },
  '📍 Top Wards by Complaints': { hi: '📍 शिकायतों के अनुसार शीर्ष वार्ड' },
  '🏆 Category Performance Summary': { hi: '🏆 श्रेणी प्रदर्शन सारांश' },
  'Share': { hi: 'हिस्सा' },
  'Performance': { hi: 'प्रदर्शन' },
  'Total': { hi: 'कुल' },

  // ── Officer Dashboard ────────────────────────────────────────────────────
  'Officer Dashboard 🧑‍💼': { hi: 'अधिकारी डैशबोर्ड 🧑‍💼' },
  'Total Assigned': { hi: 'कुल असाइन किए गए' },
  '📈 My Resolution Rate': { hi: '📈 मेरी समाधान दर' },
  'Target: 90%': { hi: 'लक्ष्य: 90%' },
  '📋 Assigned Complaints': { hi: '📋 असाइन की गई शिकायतें' },
  'SLA GUIDELINES': { hi: 'SLA दिशानिर्देश' },
  '🔄 Start': { hi: '🔄 शुरू करें' },
  '✅ Resolve': { hi: '✅ हल करें' },
  '✅ Done': { hi: '✅ पूर्ण' },
  '✅ Resolve Complaint': { hi: '✅ शिकायत हल करें' },
  'Resolution Note *': { hi: 'समाधान नोट *' },
  'Describe how the complaint was resolved, steps taken, and outcome...': { hi: 'बताएं शिकायत कैसे हल की गई, क्या कदम उठाए और परिणाम क्या रहा...' },
  '✅ Mark as Resolved': { hi: '✅ हल के रूप में चिह्नित करें' },
  '⏳ Resolving...': { hi: '⏳ हल हो रहा है...' },
  'No cases found': { hi: 'कोई मामला नहीं मिला' },
  '🧑‍💼 Field Officer': { hi: '🧑‍💼 फील्ड अधिकारी' },
  'OVERDUE': { hi: 'अतिदेय' },

  // ── Public Dashboard ─────────────────────────────────────────────────────
  'PS-CRM Public Dashboard': { hi: 'पीएस-सीआरएम सार्वजनिक डैशबोर्ड' },
  'Transparency & Accountability Portal': { hi: 'पारदर्शिता और जवाबदेही पोर्टल' },
  'Government of Delhi · Public Transparency Dashboard': { hi: 'दिल्ली सरकार · सार्वजनिक पारदर्शिता डैशबोर्ड' },
  'Public Grievance Transparency Report': { hi: 'सार्वजनिक शिकायत पारदर्शिता रिपोर्ट' },
  'Real-time complaint statistics for citizen accountability and government transparency': { hi: 'नागरिक जवाबदेही और सरकारी पारदर्शिता के लिए रियल-टाइम शिकायत आंकड़े' },
  'LIVE DATA': { hi: 'लाइव डेटा' },
  'Overview': { hi: 'अवलोकन' },
  'Categories': { hi: 'श्रेणियां' },
  'Wards': { hi: 'वार्ड' },
  'Trends': { hi: 'प्रवृत्तियां' },
  '🏛️ Government Accountability Metrics': { hi: '🏛️ सरकारी जवाबदेही मेट्रिक्स' },
  'Avg Resolution Time': { hi: 'औसत समाधान समय' },
  'SLA Compliance': { hi: 'SLA अनुपालन' },
  'Active Cases': { hi: 'सक्रिय मामले' },
  'Monthly Growth': { hi: 'मासिक वृद्धि' },
  'Citizen Satisfaction': { hi: 'नागरिक संतुष्टि' },
  'Escalation Rate': { hi: 'एस्केलेशन दर' },
  '✅ Good': { hi: '✅ अच्छा' },
  '⚠️ Monitor': { hi: '⚠️ निगरानी' },
  'Have a grievance? File it now — no login needed to track.': { hi: 'कोई शिकायत है? अभी दर्ज करें — ट्रैक करने के लिए लॉगिन की आवश्यकता नहीं।' },
  'Join thousands of citizens who resolved their complaints through PS-CRM': { hi: 'उन हजारों नागरिकों से जुड़ें जिन्होंने PS-CRM के माध्यम से अपनी शिकायतें हल कीं' },
  'SUBMISSION CHANNELS': { hi: 'जमा करने के चैनल' },
  '🔒 OTP-verified login to file & manage complaints': { hi: '🔒 शिकायतें दर्ज और प्रबंधित करने के लिए OTP-सत्यापित लॉगिन' },
  'of total': { hi: 'कुल का' },
  '📊 Category-wise Breakdown': { hi: '📊 श्रेणी-वार विश्लेषण' },
  '🎯 Resolution Status': { hi: '🎯 समाधान स्थिति' },
  '📍 Ward-wise Complaint Distribution': { hi: '📍 वार्ड-वार शिकायत वितरण' },
  '📈 Complaint Volume Trend': { hi: '📈 शिकायत मात्रा प्रवृत्ति' },
  'Track Without Login': { hi: 'बिना लॉगिन ट्रैक करें' },
  '🔍 Track a Complaint Now': { hi: '🔍 अभी शिकायत ट्रैक करें' },
  'Live Data · No Login Required': { hi: 'लाइव डेटा · लॉगिन आवश्यक नहीं' },
  '© 2025 PS-CRM · Public Transparency Dashboard · Government of Delhi': { hi: '© 2025 पीएस-सीआरएम · सार्वजनिक पारदर्शिता डैशबोर्ड · दिल्ली सरकार' },
  'Privacy Policy · Terms of Use · Accessibility': { hi: 'गोपनीयता नीति · उपयोग की शर्तें · पहुंच' },
  'Smart Public Service CRM for centralized citizen grievance management powered by AI.': { hi: 'AI द्वारा संचालित केंद्रीकृत नागरिक शिकायत प्रबंधन के लिए स्मार्ट सार्वजनिक सेवा सीआरएम।' },

  // ── Login ────────────────────────────────────────────────────────────────
  'Select Your Role': { hi: 'अपनी भूमिका चुनें' },
  'Choose your account type to continue': { hi: 'जारी रखने के लिए अपना खाता प्रकार चुनें' },
  'Enter your credentials to access the portal': { hi: 'पोर्टल तक पहुंचने के लिए अपनी जानकारी दर्ज करें' },
  'Select Role': { hi: 'भूमिका चुनें' },
  'Field Officer': { hi: 'फील्ड अधिकारी' },
  'Manage assigned cases': { hi: 'असाइन किए गए मामले प्रबंधित करें' },
  'Full system oversight': { hi: 'पूर्ण सिस्टम निगरानी' },
  'File & track complaints': { hi: 'शिकायतें दर्ज और ट्रैक करें' },
  'Continue →': { hi: 'जारी रखें →' },
  '📧 Email Address': { hi: '📧 ईमेल पता' },
  'Enter your email': { hi: 'अपना ईमेल दर्ज करें' },
  '🔒 Password': { hi: '🔒 पासवर्ड' },
  'Enter your password': { hi: 'अपना पासवर्ड दर्ज करें' },
  '✅ Login to Portal': { hi: '✅ पोर्टल में लॉगिन करें' },
  'Logging in...': { hi: 'लॉगिन हो रहा है...' },
  '← Change Role': { hi: '← भूमिका बदलें' },
  "Don't have an account?": { hi: 'खाता नहीं है?' },
  'Register here': { hi: 'यहाँ पंजीकरण करें' },
  'Transparent Governance Starts Here': { hi: 'पारदर्शी शासन यहाँ से शुरू होता है' },
  'File complaints, track resolutions, and hold your government accountable — all in one place.': { hi: 'शिकायतें दर्ज करें, समाधान ट्रैक करें, और अपनी सरकार को जवाबदेह बनाएं — सब एक जगह।' },
  'Complaints Resolved': { hi: 'शिकायतें हल की गईं' },
  'Average Response': { hi: 'औसत प्रतिक्रिया' },

  // ── Register ─────────────────────────────────────────────────────────────
  'Create Account': { hi: 'खाता बनाएं' },
  'Register as a citizen to access the portal': { hi: 'पोर्टल तक पहुंचने के लिए नागरिक के रूप में पंजीकरण करें' },
  '👤 Full Name *': { hi: '👤 पूरा नाम *' },
  '📱 Phone Number': { hi: '📱 फ़ोन नंबर' },
  '📧 Email Address *': { hi: '📧 ईमेल पता *' },
  'Your email address': { hi: 'आपका ईमेल पता' },
  '🔒 Password *': { hi: '🔒 पासवर्ड *' },
  'Min 6 characters': { hi: 'न्यूनतम 6 अक्षर' },
  '🔒 Confirm Password *': { hi: '🔒 पासवर्ड की पुष्टि करें *' },
  'Repeat password': { hi: 'पासवर्ड दोबारा दर्ज करें' },
  'Terms of Service': { hi: 'सेवा की शर्तें' },
  'Privacy Policy': { hi: 'गोपनीयता नीति' },
  '✅ Create Account': { hi: '✅ खाता बनाएं' },
  '⏳ Creating Account...': { hi: '⏳ खाता बन रहा है...' },
  'Already have an account?': { hi: 'पहले से खाता है?' },
  'Sign in here': { hi: 'यहाँ साइन इन करें' },
  'or': { hi: 'या' },
  '🌐 Continue as Guest (View Public Dashboard)': { hi: '🌐 अतिथि के रूप में जारी रखें (सार्वजनिक डैशबोर्ड देखें)' },
  'Join the Digital Governance Platform': { hi: 'डिजिटल शासन प्लेटफ़ॉर्म से जुड़ें' },
  'Register as a citizen to file complaints, track resolutions, and hold your government accountable.': { hi: 'शिकायतें दर्ज करने, समाधान ट्रैक करने और अपनी सरकार को जवाबदेह बनाने के लिए नागरिक के रूप में पंजीकरण करें।' },
  'File complaints in minutes': { hi: 'मिनटों में शिकायतें दर्ज करें' },
  'Real-time status tracking': { hi: 'रियल-टाइम स्थिति ट्रैकिंग' },
  'Instant email notifications': { hi: 'तत्काल ईमेल सूचनाएं' },
  'Rate your experience': { hi: 'अपना अनुभव रेट करें' },
  'Please fill all required fields': { hi: 'कृपया सभी आवश्यक फ़ील्ड भरें' },
  'Passwords do not match': { hi: 'पासवर्ड मेल नहीं खाते' },
  'Password must be at least 6 characters': { hi: 'पासवर्ड कम से कम 6 अक्षरों का होना चाहिए' },

  // ── Notifications ────────────────────────────────────────────────────────
  '🔔 Notifications': { hi: '🔔 सूचनाएं' },
  'You have': { hi: 'आपके पास' },
  'unread notification': { hi: 'अपठित सूचना' },
  'unread notifications': { hi: 'अपठित सूचनाएं' },
  "All caught up!": { hi: 'सब पढ़ लिया!' },
  '✓ Mark All Read': { hi: '✓ सभी पढ़ा हुआ चिह्नित करें' },
  'Unread': { hi: 'अपठित' },
  '✅ Resolved': { hi: '✅ हल किया गया' },
  '🔄 Status Updates': { hi: '🔄 स्थिति अपडेट' },
  '🚨 Escalated': { hi: '🚨 एस्केलेट किया गया' },
  'No notifications': { hi: 'कोई सूचना नहीं' },
  "You're all caught up!": { hi: 'आपने सब पढ़ लिया है!' },
  'Complaint Registered': { hi: 'शिकायत पंजीकृत' },
  'Complaint In Progress': { hi: 'शिकायत प्रगति में' },
  'Complaint Escalated': { hi: 'शिकायत एस्केलेट की गई' },
  'Complaint Rejected': { hi: 'शिकायत अस्वीकृत' },
  '⭐ Give Feedback →': { hi: '⭐ फ़ीडबैक दें →' },
  'Click here to view': { hi: 'देखने के लिए यहां क्लिक करें' },
  'Title': { hi: 'शीर्षक' },
  'Priority': { hi: 'प्राथमिकता' },
  'Duplicate Complaint Check': { hi: 'डुप्लिकेट शिकायत जांच' },
  'Please check the following complaint ID for duplicates:': { hi: 'कृपया निम्नलिखित शिकायत आईडी की डुप्लिकेट जांच करें:' },
  'Email': { hi: 'ईमेल' },
  'Your email': { hi: 'आपका ईमेल' },
  '📧 Send to Email': { hi: '📧 ईमेल भेजें' },
  '🔍 Track Complaint →': { hi: '🔍 शिकायत ट्रैक करें →' },
  '🚨 View Complaint →': { hi: '🚨 शिकायत देखें →' },
  'Portal': { hi: 'पोर्टल' },
  '🏛️ Administrator': { hi: '🏛️ प्रशासक' },
};

// ─── Helper function ───────────────────────────────────────────────────────────
export function tx(key, lang) {
  if (lang === 'en') return key;
  return t[key]?.hi || key;
}